# Generated by Django 5.1.1 on 2024-10-01 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk_app', '0002_rename_harga_beli_produk_harga_khusus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('total_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jenis_harga', models.CharField(choices=[('umum', 'Harga Umum'), ('khusus', 'Harga Khusus')], max_length=20)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk_app.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaksi_app.transaksi')),
            ],
        ),
    ]
