# Generated by Django 5.1.1 on 2024-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0002_alter_transaksi_total_bayar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='tanggal_transaksi',
            new_name='tanggal',
        ),
        migrations.RenameField(
            model_name='transaksi',
            old_name='petugas',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='total_bayar',
        ),
        migrations.RemoveField(
            model_name='transaksiitem',
            name='jenis_harga',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='pelanggan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaksiitem',
            name='tipe_harga',
            field=models.CharField(choices=[('khusus', 'Harga Khusus'), ('umum', 'Harga Umum')], default='umum', max_length=6),
        ),
    ]
