# Generated by Django 5.1.1 on 2024-10-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0003_rename_tanggal_transaksi_transaksi_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksiitem',
            name='harga',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaksiitem',
            name='tipe_harga',
            field=models.CharField(choices=[('harga_khusus', 'Harga Khusus'), ('harga_umum', 'Harga Umum')], default='harga_umum', max_length=20),
        ),
    ]
