# Generated by Django 5.1.1 on 2024-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0004_alter_transaksiitem_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
    ]
