# Generated by Django 5.1.1 on 2024-10-30 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk_app', '0008_alter_kategori_options'),
        ('transaksi_app', '0006_alter_transaksi_total_harga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pelanggan', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('tipe_harga', models.CharField(choices=[('harga_khusus', 'Harga Khusus'), ('harga_umum', 'Harga Umum')], default='harga_umum', max_length=20)),
                ('harga', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaksi_app.cart')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk_app.produk')),
            ],
        ),
    ]
