# Generated by Django 5.1.1 on 2024-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='selesai', max_length=10),
        ),
    ]
