# Generated by Django 5.1.1 on 2024-10-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0008_transaksi_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggan', models.CharField(max_length=255)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaksi_app.transaksi')),
            ],
        ),
    ]
