# Generated by Django 5.1.1 on 2024-10-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0009_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='produk',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transaksi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='status',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
