# Generated by Django 5.1.1 on 2024-10-30 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk_app', '0008_alter_kategori_options'),
        ('transaksi_app', '0010_remove_cartitem_cart_remove_cartitem_produk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk_app.produk')),
            ],
        ),
    ]
