# Generated by Django 5.1.1 on 2024-10-30 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk_app', '0008_alter_kategori_options'),
        ('transaksi_app', '0011_keranjang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('tipe_harga', models.CharField(choices=[('harga_umum', 'Harga Umum'), ('harga_khusus', 'Harga Khusus')], max_length=20)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk_app.produk')),
            ],
        ),
        migrations.DeleteModel(
            name='Keranjang',
        ),
    ]
