# Generated by Django 5.1.1 on 2024-10-31 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0012_cartitem_delete_keranjang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=50, unique=True)),
                ('tanggal_invoice', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pelanggan', models.CharField(max_length=255)),
                ('status', models.CharField(default='Belum Dibayar', max_length=50)),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='transaksi_app.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaksi_app.invoice')),
                ('transaksi_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi_app.transaksiitem')),
            ],
        ),
    ]
