# Generated by Django 5.1.1 on 2024-11-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0013_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='transaksi_item',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaksi_app.cartitem'),
        ),
    ]
