# Generated by Django 5.1.1 on 2024-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0014_remove_invoiceitem_transaksi_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Sudah Dibayar', 'Sudah Dibayar'), ('Dibatalkan', 'Dibatalkan')], default='Belum Dibayar', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
