# Generated by Django 5.1.1 on 2024-11-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_app', '0015_alter_invoice_status_alter_invoice_total_harga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Item Invoice', 'verbose_name_plural': 'Item Invoice'},
        ),
    ]
