# Generated by Django 5.1.1 on 2024-10-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk_app.kategori')),
            ],
        ),
    ]
