# Generated by Django 5.1.1 on 2024-10-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk_app', '0003_produk_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perubahan', models.IntegerField()),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk_app.produk')),
            ],
            options={
                'verbose_name': 'Log Perubahan Stok',
                'verbose_name_plural': 'Log Perubahan Stok',
                'ordering': ['-created_at'],
            },
        ),
    ]
